apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
spec:
  type: {{SERVICE_TYPE}}    # "ClusterIP", "NodePort" (local), or "LoadBalancer" (EKS)
  selector:
    app: ml-model
  ports:
  - port: 8501
    targetPort: 8501
